export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const COMENZAR_DESCARGAS_PRODUCTOS = "COMENZAR_DESCARGAS_PRODUCTOS";
export const COMENZAR_DESCARGAS_EXITO = "COMENZAR_DESCARGAS_EXITO";
export const COMENZAR_DESCARGAS_ERROR = "COMENZAR_DESCARGAS_ERROR";

export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ELIMINAR_PRODUCTO_EXITO = "ELIMINAR_PRODUCTO_EXITO";
export const ELIMINAR_PRODUCTO_ERROR = "ELIMINAR_PRODUCTO_ERROR";

export const OBTENER_PRODUCTO_EDITAR = "OBTENER_PRODUCTO_EDITAR";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const EDITAR_PRODUCTO_EXITO = "EDITAR_PRODUCTO_EXITO";
export const EDITAR_PRODUCTO_ERROR = "EDITAR_PRODUCTO_ERROR";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
